# Generated by Django 5.2.9 on 2025-12-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor'), ('alumni', 'Alumni'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
