# Generated by Django 5.2.9 on 2025-12-16 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_assignment_assignment_type_assignment_created_at_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='attendance',
            name='class_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.classschedule'),
        ),
    ]
